rmq:
  namesrv:
    addr: 127.0.0.1:9876
  group:
    cart: cartGroup
  instanceName:
    cart: cart
  topic:
    orderCreated: ORDER_CREATED


spring:
  application:
    name: cart
  profiles:
    active: prod
#    active: @profiles.active@

management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        # exclude:
        include: "*"
      base-path: /actuator

eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
  instance:
    appname: ${spring.application.name}
    instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    status-page-url-path: ${management.endpoints.web.base-path}/info
    health-check-url-path: ${management.endpoints.web.base-path}/health
    metadata-map:
      zone: primary # This is needed for the load balancer
      profile: ${spring.profiles.active}
      version: ${info.project.version}

ribbon:
  eureka:
    enabled: true
  ConnectTimeout: 5000
  ReadTimeout: 5000
  MaxTotalConnections: 600
  MaxConnectionsPerHost: 200

hystrix:
  share-security-context: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
